### ISSUE TITLE
blank page and browser errors

### ISSUE THREAD

**Issue by decentropy** [adadgio/neo4j-js-ng2#24]
Only a blank dark grey page is rendered, and I see the following browser errors. Any ideas?

I don' think it's my neo4j.settings.json, because I got the older javascript-based project to connect.

```
core.es5.js:1020 ERROR Error: Uncaught (in promise): Error: SyntaxError: Unexpected token a in JSON at position 26
Error: SyntaxError: Unexpected token a in JSON at position 26
    at bootstrap.ts:28:27
    at webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:392:1)
    at Object.onInvoke (core.es5.js:3890:1)
    at webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391:1)
    at webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run (zone.js:142:1)
    at zone.js:873:1
    at webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:425:1)
    at Object.onInvokeTask (core.es5.js:3881:1)
    at webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424:1)
    at webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:192:1)
    at resolvePromise (zone.js:824:1)
    at zone.js:876:1
    at webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:425:1)
    at Object.onInvokeTask (core.es5.js:3881:1)
    at webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424:1)
    at webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:192:1)
    at drainMicroTaskQueue (zone.js:602:1)
    at webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:503:1)
    at invokeTask (zone.js:1540:1)
    at XMLHttpRequest.globalZoneAwareCallback (zone.js:1566:1)
```

**Comment by decentropy** [comment]
My bad... I had an extra comma in the config
